# Purpose of script: This script was developed by the Evans School Policy Analysis & Research Group (EPAR) to extract basic grant 
# information from Gates Foundation's grant "Proposal Narratives", a template for which is publicly found here: 
# https://www.gatesfoundation.org/~/media/GFO/How-We-Work/RFP/Polio-Lessons-RFP_Proposal-Narrative.docx?la=en

# Authors: Rohit Gupta, Muel Kiel, and Namrata Kolla
# Date: 24 October 2018

# Inputs: CSV file generated by the portfolio scraper script
# Outputs: Map for countries and regions of intervention

###############################################################
# LINES LIKE THESE MARK PLACES WHERE USERS MUST PROVIDE INPUT #
###############################################################

#clear workspace
rm(list = ls())

#getting packages installed/loaded
packages <- c("rworldmap")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}

#load packages
library("rworldmap")

################ input space ####################

#setting the work directory
setwd("\\\\netid.washington.edu/wfs/EvansEPAR/Project/EPAR/Working Files/372 - EPAR Tools Development/Code/334/")

#################################################

#reading the file with the information for country/region of intervention
#need to manually update the missing info for country of intervention (if any)
scraping_res <- read.csv("scraping_result.csv")

#getting the relevant columns
sel_var <- c("Country_of_Intervention", "Region", "Country_Intervention_ISO")
country_region <- scraping_res[sel_var]
country_region$Count <- 1

#making a dataframe at a country level, taking counts
country_agg <- as.data.frame(aggregate(Count ~ Country_of_Intervention + Region + Country_Intervention_ISO, 
                                       data = country_region, FUN = sum))

#making a country map
country_info_map <- joinCountryData2Map(country_agg, joinCode = "ISO3", 
                                        nameJoinColumn = "Country_Intervention_ISO")
#plotting the map now
#opening the file on disk
png("country_map.png", width = 1200, height = 1200)
mapCountryData(country_info_map, nameColumnToPlot = "Count", xlim = c(-20,120), ylim = c(10,25), 
               catMethod = "fixedWidth", mapTitle = 'Countries of Intervention',
               oceanCol = "lightblue", missingCountryCol = "white")
#closing the file on disk
dev.off()

#making a region map

#plotting the map now
#opening the file on disk
png("region_map.png", width = 1200, height = 1200)
mapByRegion(country_agg, nameDataColumn = "Count", joinCode = "ISO3", 
            nameJoinColumn = "Country_Intervention_ISO", regionType = "GBD",
            FUN = 'sum', xlim = c(-20,120), ylim = c(10,25), 
            mapTitle = "Regions of Intervention", catMethod="fixedWidth",
            oceanCol = "lightblue", missingCountryCol = "white")
mtext("World Regions broken down by GBD: http://atlas.iapb.org/wp-content/uploads/GBD-21-Regions-Map.pdf",side=1,line=-1)
#closing the file on disk
dev.off()

#################################################

